apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
  labels:
    name: web
    app: todoapp

spec:
  replicas: 2
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web 
        image: rohithreddyj/todo-app
        ports:
        - containerPort: 3000
